Order module implementation
hex-arch-training/hex-thai-star pull request #42
Opened 2021-10-25 20:38 UTC by JanuszTaterka

Implemented a complete (i.e. all layers) order component including some base use case and cross-module communication

2021-11-10 10:10 UTC, JanuszTaterka commented on common/common-domain/src/main/java/io/github/hexarchtraining/hts/common/domain/token/TokenType.java
> +    INVITED_GUEST
Please hav a look on CreateOrderService L:42 and decide if we want to duplicate the Token Type

2021-11-17 08:27 UTC, maciejmalecki approved these changes

2021-11-24 14:21 UTC, jczas commented on common/common-domain/src/main/java/io/github/hexarchtraining/hts/common/domain/token/TokenType.java
> +    INVITED_GUEST
I dont see usage of TokenType in domain booking.
Do we need this TokenTyp.e The name is not very helpfull.
Mayby we use simply boolean flag: 
invitedGuest: true/false

2021-11-24 14:25 UTC, jczas requested changes
Added comment

2022-01-12 10:46 UTC, jczas approved these changes

2022-01-12 11:03 UTC, merged